<%
 homepage_title= "后台管理系统"
 homepage_caption= "后台管理系统"
 homepage_link= "http://"
 your_email= ""
 creattime= "20090704"
 news_back_count= "12"
 news_front_count= "12"
 news_permission= "no"
 products_back_count= "12"
 products_front_count= "6"
 imageswidth= "120"
 imagesheight= "140"
 b_imageswidth= "500"
 b_imagesheight= "500"
 products_permission= "no"
%>